#!/usr/bin/env bash
#
# Deploy strategon agents one-after-another from certs/machine.json.
#
#   deploy/install-agents.sh --region <default> [machine-key ...]
#   deploy/install-agents.sh --region jp
#   deploy/install-agents.sh --region jp ori-1 ori-2
#   deploy/install-agents.sh --check --region jp
#
# Each JSON entry:
#
#   {
#     "ori-1": {
#       "name": "ori-1",          # machine-id (cert CN); defaults to the key
#       "user": "ubuntu",
#       "hostname": "ec2-....amazonaws.com",
#       "port": 22,                 # optional, default 22
#       "identity": "~/.ssh/key", # optional SSH private key
#       "region": "jp"            # optional; overrides --region for this host
#     }
#   }
#
# Builds a temporary SSH config so install-agent.sh can reach hosts that need
# a non-default port or IdentityFile, then calls install-agent.sh sequentially.
# Stops on the first failure.
set -euo pipefail

cd "$(dirname "$0")/.."

MACHINES_JSON="${STRATEGON_MACHINES_JSON:-./certs/machine.json}"
INSTALL="$(dirname "$0")/install-agent.sh"

CHECK_ONLY=false
DEFAULT_REGION=""
KEYS=()

usage() {
  sed -n '2,28p' "$0" | sed 's/^# \?//'
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_ONLY=true; shift ;;
    --region)
      [[ $# -ge 2 ]] || usage
      DEFAULT_REGION="$2"
      shift 2
      ;;
    -h|--help) usage ;;
    --) shift; break ;;
    -*)
      printf 'error: unknown flag %q\n' "$1" >&2
      usage
      ;;
    *) KEYS+=("$1"); shift ;;
  esac
done
KEYS+=("$@")

[[ -f "$MACHINES_JSON" ]] || {
  printf 'error: machines file not found: %s\n' "$MACHINES_JSON" >&2
  exit 2
}
command -v jq >/dev/null || {
  printf 'error: jq is required to parse %s\n' "$MACHINES_JSON" >&2
  exit 2
}
[[ -x "$INSTALL" || -f "$INSTALL" ]] || {
  printf 'error: install-agent.sh not found at %s\n' "$INSTALL" >&2
  exit 2
}

# All keys, insertion order preserved by jq.
ALL_KEYS=()
while IFS= read -r k; do
  ALL_KEYS+=("$k")
done < <(jq -r 'keys_unsorted[]' "$MACHINES_JSON")

if [[ ${#KEYS[@]} -eq 0 ]]; then
  KEYS=("${ALL_KEYS[@]}")
else
  for k in "${KEYS[@]}"; do
    jq -e --arg k "$k" 'has($k)' "$MACHINES_JSON" >/dev/null \
      || { printf 'error: unknown machine key %q in %s\n' "$k" "$MACHINES_JSON" >&2; exit 2; }
  done
fi

[[ ${#KEYS[@]} -gt 0 ]] || {
  printf 'error: no machines to deploy\n' >&2
  exit 2
}

SSH_CONFIG="$(mktemp -t strategon-ssh.XXXXXX)"
trap 'rm -f "$SSH_CONFIG"' EXIT

# One Host stanza per selected machine. Host alias == JSON key so install-agent
# can take TARGET=<key>.
{
  printf '# generated by deploy/install-agents.sh — do not edit\n'
  for key in "${KEYS[@]}"; do
    user="$(jq -r --arg k "$key" '.[$k].user // empty' "$MACHINES_JSON")"
    host="$(jq -r --arg k "$key" '.[$k].hostname // empty' "$MACHINES_JSON")"
    port="$(jq -r --arg k "$key" '.[$k].port // 22' "$MACHINES_JSON")"
    identity="$(jq -r --arg k "$key" '.[$k].identity // empty' "$MACHINES_JSON")"

    [[ -n "$user" ]] || { printf 'error: %s: missing user\n' "$key" >&2; exit 2; }
    [[ -n "$host" ]] || { printf 'error: %s: missing hostname\n' "$key" >&2; exit 2; }

    # Expand a leading "~/" — neither "$identity" nor ${var#~/} tilde-expands
    # the way we need (the latter expands ~/ in the pattern to $HOME/).
    if [[ -n "$identity" && "$identity" == '~/'* ]]; then
      identity="${HOME}/${identity#\~/}"
    fi

    printf '\nHost %s\n' "$key"
    printf '  HostName %s\n' "$host"
    printf '  User %s\n' "$user"
    printf '  Port %s\n' "$port"
    printf '  BatchMode yes\n'
    printf '  StrictHostKeyChecking accept-new\n'
    if [[ -n "$identity" ]]; then
      [[ -f "$identity" ]] || {
        printf 'error: %s: identity file not found: %s\n' "$key" "$identity" >&2
        exit 2
      }
      printf '  IdentityFile %s\n' "$identity"
      printf '  IdentitiesOnly yes\n'
    fi
  done
} >"$SSH_CONFIG"

export STRATEGON_SSH_CONFIG="$SSH_CONFIG"

printf 'Fleet deploy: %d host(s) from %s\n' "${#KEYS[@]}" "$MACHINES_JSON"
FAILED=0
OK=0
SKIPPED=0

for key in "${KEYS[@]}"; do
  machine_id="$(jq -r --arg k "$key" '.[$k].name // $k' "$MACHINES_JSON")"
  region="$(jq -r --arg k "$key" '.[$k].region // empty' "$MACHINES_JSON")"
  if [[ -z "$region" ]]; then
    region="$DEFAULT_REGION"
  fi
  if [[ -z "$region" ]]; then
    printf 'error: %s: no region (set "region" in JSON or pass --region)\n' "$key" >&2
    exit 2
  fi

  host="$(jq -r --arg k "$key" '.[$k].hostname' "$MACHINES_JSON")"
  printf '\n######## %s → %s (machine-id=%s region=%s) ########\n' \
    "$key" "$host" "$machine_id" "$region"

  args=()
  $CHECK_ONLY && args+=(--check)
  args+=("$key" "$machine_id" "$region")

  if bash "$INSTALL" "${args[@]}"; then
    OK=$((OK + 1))
  else
    rc=$?
    FAILED=$((FAILED + 1))
    printf 'error: install failed for %s (exit %d); stopping fleet deploy\n' "$key" "$rc" >&2
    printf 'summary: ok=%d failed=%d remaining_skipped=%d\n' \
      "$OK" "$FAILED" "$((${#KEYS[@]} - OK - FAILED))" >&2
    exit "$rc"
  fi
done

printf '\nFleet deploy complete: ok=%d failed=%d\n' "$OK" "$FAILED"
